-- Aux tables
CREATE TABLE IF NOT EXISTS vlans (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vlan_id INTEGER NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT vlans_vlan_id_unique UNIQUE (vlan_id)
);

CREATE TABLE IF NOT EXISTS odbs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES locations(id),
  name TEXT NOT NULL,
  address TEXT,
  reference TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- onus service/metadata columns
ALTER TABLE IF EXISTS onus
  ADD COLUMN IF NOT EXISTS onu_index INTEGER,
  ADD COLUMN IF NOT EXISTS mode TEXT,
  ADD COLUMN IF NOT EXISTS vlan_id INTEGER,
  ADD COLUMN IF NOT EXISTS tr069_enabled BOOLEAN,
  ADD COLUMN IF NOT EXISTS catv_enabled BOOLEAN,
  ADD COLUMN IF NOT EXISTS voip_enabled BOOLEAN,
  ADD COLUMN IF NOT EXISTS mgmt_ip TEXT,
  ADD COLUMN IF NOT EXISTS odb_splitter TEXT,
  ADD COLUMN IF NOT EXISTS odb_id BIGINT REFERENCES odbs(id),
  ADD COLUMN IF NOT EXISTS pon_type TEXT,
  ADD COLUMN IF NOT EXISTS download_profile TEXT,
  ADD COLUMN IF NOT EXISTS upload_profile TEXT,
  ADD COLUMN IF NOT EXISTS profile TEXT;

