CREATE TABLE IF NOT EXISTS speed_profiles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  download_mbps INTEGER NOT NULL DEFAULT 0,
  upload_mbps INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS speed_profiles_name_unique ON speed_profiles(name);

